%% Options for Building EEG.event.code numeric id
% The code is [trial_type mem_bin cur_task]
% Expand on possible codes here. 
% A code of 1111 = ab, hh, artist trial
% A code of 3221 = de, h, artist trial
% A code of 2134 = ac, hm, vacation trial
% A cod

% Trial type ID numbers
type_bin = struct( ...
    'ab', 1, ...
    'ac', 2, ...
    'de', 3 );

% Memory bin ID numbers
mem_bin = struct( ...
    'HH2',   21, ...
    'HM2',   22, ...
    'HM1',   22, ...
    'MH2',   23, ...
    'MH1',   23, ...
    'MM2',   24, ...
    'MM1',   24, ...
    'MM0',   24, ...
    'MISS2', 25, ...
    'H2',    99, ...
    'H1',    11, ...
    'M2',    99, ...
    'M1',    12, ...
    'M0',    12, ...
    'MISS1', 13 );

% Current task bin
task_bin = struct( ...
    'artist', 1, ...
    'function', 2, ...
    'pleasant', 3, ...
    'vacation', 4 );



% Update EEG.event with new codes
for evti = 1:length(EEG.event)
    
    % Get the current trial
    cur_event = EEG.event(evti);
    
    % Determine trial type
    this_mem = cur_event.memory_bin;
    this_type = cur_event.trial_type;
    this_task = cur_event.cur_task;
    
    % Update type and code in current trial
    cur_event.type = str2double(sprintf('%d%d%d', type_bin.(this_type), mem_bin.(this_mem), task_bin.(this_task)));
    cur_event.code = sprintf('%s-%s-%s',this_type,this_mem,this_task);
    
    % Update EEG.event(evti)
    EEG.event(evti) = cur_event;
    
end